language: java

jdk:
  - openjdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_65a7c73dbbef_key -iv $encrypted_65a7c73dbbef_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

after_success:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then gradle uploadArchives; fi

